package com.struggler.common.model;

import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * Table: sys_dict
 */
@Data
@TableName("sys_dict")
public class SysDict implements Serializable {
    /**
     * Table:     sys_dict
     * Column:    id
     * Nullable:  false
     */
    private Integer id;

    /**
     * 字典编码
     *
     * Table:     sys_dict
     * Column:    dic_code
     * Nullable:  true
     */
    private String dicCode;

    /**
     * 字典名称
     *
     * Table:     sys_dict
     * Column:    dic_name
     * Nullable:  true
     */
    private String dicName;

    /**
     * 字典项是否启用(数据字典pub_y_n:<y:是,n:否>)
     *
     * Table:     sys_dict
     * Column:    dic_flag
     * Nullable:  true
     */
    private String dicFlag;

    /**
     * 字典项编码
     *
     * Table:     sys_dict
     * Column:    item_code
     * Nullable:  true
     */
    private String itemCode;

    /**
     * 字典项值
     *
     * Table:     sys_dict
     * Column:    item_value
     * Nullable:  true
     */
    private String itemValue;

    /**
     * 字典项排序
     *
     * Table:     sys_dict
     * Column:    item_seq
     * Nullable:  true
     */
    private Integer itemSeq;

    /**
     * 字典项是否启用(数据字典pub_y_n:<y:是,n:否>)
     *
     * Table:     sys_dict
     * Column:    item_flag
     * Nullable:  true
     */
    private String itemFlag;

    /**
     * 字典描述
     *
     * Table:     sys_dict
     * Column:    dic_comments
     * Nullable:  true
     */
    private String dicComments;

    /**
     * 创建人id
     *
     * Table:     sys_dict
     * Column:    created_by
     * Nullable:  true
     */
    private Integer createdBy;

    /**
     * Table:     sys_dict
     * Column:    created_date
     * Nullable:  false
     */
    private Date createdDate;

    /**
     * 更新人id
     *
     * Table:     sys_dict
     * Column:    updated_by
     * Nullable:  false
     */
    private Integer updatedBy;

    /**
     * Table:     sys_dict
     * Column:    updated_date
     * Nullable:  false
     */
    private Date updatedDate;

    /**
     * 是否字典头标志(数据字典pub_y_n:<y:是,n:否>)
     *
     * Table:     sys_dict
     * Column:    is_head_flag
     * Nullable:  true
     */
    private String isHeadFlag;

    /**
     * 模块类型
     *
     * Table:     sys_dict
     * Column:    model_type
     * Nullable:  true
     */
    private String modelType;

    @TableField(exist = false)
    private List<Map<String,Object>> itemBean;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jul 05 15:45:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jul 05 15:45:42 CST 2019
     */
    public SysDict(Integer id, Integer updatedBy, String dicCode, String dicName, String dicFlag, String itemCode, String itemValue, Integer itemSeq, String itemFlag, String dicComments, Integer createdBy, Date createdDate, Date updatedDate, String isHeadFlag, String modelType,List<Map<String,Object>> itemBean) {
        this.id = id;
        this.dicCode = dicCode;
        this.dicName = dicName;
        this.dicFlag = dicFlag;
        this.itemCode = itemCode;
        this.itemValue = itemValue;
        this.itemSeq = itemSeq;
        this.itemFlag = itemFlag;
        this.dicComments = dicComments;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedBy = updatedBy;
        this.updatedDate = updatedDate;
        this.isHeadFlag = isHeadFlag;
        this.modelType = modelType;
        this.itemBean = itemBean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict
     *
     * @mbggenerated Fri Jul 05 15:45:42 CST 2019
     */
    public SysDict() {
        super();
    }
}
