package com.struggler.common.model;

import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.IdType;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * Table: sys_menu
 */
@Data
@TableName("sys_menu")
public class SysMenu implements Serializable {
    /**
     * Table:     sys_menu
     * Column:    id
     * Nullable:  false
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 父菜单ID，一级菜单为0
     *
     * Table:     sys_menu
     * Column:    parent_id
     * Nullable:  true
     */
    private Long parentId;

    /**
     * 父菜单名称
     */
    @TableField(exist=false)
    private String parentName;

    /**
     * 菜单名称
     *
     * Table:     sys_menu
     * Column:    name
     * Nullable:  true
     */
    private String name;

    /**
     * 菜单URL
     *
     * Table:     sys_menu
     * Column:    url
     * Nullable:  true
     */
    private String url;

    /**
     * 授权(多个用逗号分隔，如：user:list,user:create)
     *
     * Table:     sys_menu
     * Column:    permissions
     * Nullable:  true
     */
    private String permissions;

    /**
     * 类型   10：目录   20：菜单   30：按钮
     *
     * Table:     sys_menu
     * Column:    type
     * Nullable:  true
     */
    private String type;

    /**
     * 菜单图标
     *
     * Table:     sys_menu
     * Column:    icon
     * Nullable:  true
     */
    private String icon;

    /**
     * 排序
     *
     * Table:     sys_menu
     * Column:    sort
     * Nullable:  true
     */
    private Long sort;

    /**
     * 菜单状态 Y启用 N禁用
     *
     * Table:     sys_menu
     * Column:    status
     * Nullable:  true
     */
    private String status;

    /**
     * 菜单描述
     *
     * Table:     sys_menu
     * Column:    comments
     * Nullable:  true
     */
    private String comments;

    /**
     * 创建人
     *
     * Table:     sys_menu
     * Column:    created_by
     * Nullable:  true
     */
    private Long createdBy;

    /**
     * 创建时间
     *
     * Table:     sys_menu
     * Column:    created_date
     * Nullable:  true
     */
    private Date createdDate;

    /**
     * 修改人
     *
     * Table:     sys_menu
     * Column:    updated_by
     * Nullable:  true
     */
    private Long updatedBy;

    /**
     * 修改时间
     *
     * Table:     sys_menu
     * Column:    updated_date
     * Nullable:  true
     */
    private Date updatedDate;

    /**
     * ztree属性
     */
    @TableField(exist=false)
    private Boolean open;

    @TableField(exist=false)
    private List<?> children;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_menu
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    public SysMenu(Long id, Long parentId, String name, String url, String permissions, String type, String icon, Long sort, String status, String comments, Long createdBy, Date createdDate, Long updatedBy, Date updatedDate) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.url = url;
        this.permissions = permissions;
        this.type = type;
        this.icon = icon;
        this.sort = sort;
        this.status = status;
        this.comments = comments;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedBy = updatedBy;
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    public SysMenu() {
        super();
    }
}
