package com.struggler.common.model;

import com.baomidou.mybatisplus.annotations.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Table: sys_serial_number
 */
@Data
@TableName("sys_serial_number")
public class SysSerialNumber implements Serializable {
    /**
     * 主键 主键
     *
     * Table:     sys_serial_number
     * Column:    id
     * Nullable:  false
     */
    private Long id;

    /**
     * 乐观锁 乐观锁
     *
     * Table:     sys_serial_number
     * Column:    revision
     * Nullable:  true
     */
    private Long revision;

    /**
     * 创建人 创建人
     *
     * Table:     sys_serial_number
     * Column:    created_by
     * Nullable:  true
     */
    private String createdBy;

    /**
     * 创建时间 创建时间
     *
     * Table:     sys_serial_number
     * Column:    created_date
     * Nullable:  true
     */
    private Date createdDate;

    /**
     * 更新人 更新人
     *
     * Table:     sys_serial_number
     * Column:    updated_by
     * Nullable:  true
     */
    private String updatedBy;

    /**
     * 更新时间 更新时间
     *
     * Table:     sys_serial_number
     * Column:    updated_date
     * Nullable:  true
     */
    private Date updatedDate;

    /**
     * 删除状态:[-9:已删除,0:正常] 删除状态:[-9:已删除,0:正常]
     *
     * Table:     sys_serial_number
     * Column:    state
     * Nullable:  true
     */
    private Integer state;

    /**
     * 规则编号
     *
     * Table:     sys_serial_number
     * Column:    rule_code
     * Nullable:  true
     */
    private String ruleCode;

    /**
     * 规则名称
     *
     * Table:     sys_serial_number
     * Column:    rule_name
     * Nullable:  true
     */
    private String ruleName;

    /**
     * 规则类型
     *
     * Table:     sys_serial_number
     * Column:    rule_type
     * Nullable:  true
     */
    private String ruleType;

    /**
     * 编码长度
     *
     * Table:     sys_serial_number
     * Column:    serial_length
     * Nullable:  true
     */
    private Integer serialLength;

    /**
     * 当前值
     *
     * Table:     sys_serial_number
     * Column:    current_value
     * Nullable:  true
     */
    private String currentValue;

    /**
     * 初始值
     *
     * Table:     sys_serial_number
     * Column:    init_value
     * Nullable:  true
     */
    private String initValue;

    /**
     * 步长
     *
     * Table:     sys_serial_number
     * Column:    step
     * Nullable:  true
     */
    private Integer step;

    /**
     * 系统时间
     *
     * Table:     sys_serial_number
     * Column:    system_time
     * Nullable:  true
     */
    private Date systemTime;

    /**
     * 前缀
     *
     * Table:     sys_serial_number
     * Column:    prefix
     * Nullable:  true
     */
    private String prefix;

    /**
     * 分割
     *
     * Table:     sys_serial_number
     * Column:    split
     * Nullable:  true
     */
    private String split;

    /**
     * Table:     sys_serial_number
     * Column:    created_dept
     * Nullable:  true
     */
    private String createdDept;

    /**
     * Table:     sys_serial_number
     * Column:    cur_time
     * Nullable:  true
     */
    private Date curTime;

    /**
     * 规则类型名称
     *
     * Table:     sys_serial_number
     * Column:    rule_type_name
     * Nullable:  true
     */
    private String ruleTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_serial_number
     *
     * @mbggenerated Thu Jul 11 15:01:46 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_serial_number
     *
     * @mbggenerated Thu Jul 11 15:01:46 CST 2019
     */
    public SysSerialNumber(Long id, Long revision, String createdBy, Date createdDate, String updatedBy, Date updatedDate, Integer state, String ruleCode, String ruleName, String ruleType, Integer serialLength, String currentValue, String initValue, Integer step, Date systemTime, String prefix, String split, String createdDept, Date curTime, String ruleTypeName) {
        this.id = id;
        this.revision = revision;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedBy = updatedBy;
        this.updatedDate = updatedDate;
        this.state = state;
        this.ruleCode = ruleCode;
        this.ruleName = ruleName;
        this.ruleType = ruleType;
        this.serialLength = serialLength;
        this.currentValue = currentValue;
        this.initValue = initValue;
        this.step = step;
        this.systemTime = systemTime;
        this.prefix = prefix;
        this.split = split;
        this.createdDept = createdDept;
        this.curTime = curTime;
        this.ruleTypeName = ruleTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_serial_number
     *
     * @mbggenerated Thu Jul 11 15:01:46 CST 2019
     */
    public SysSerialNumber() {
        super();
    }
}
