package com.struggler.common.model;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.IdType;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Table: sys_user_role
 */
@Data
@TableName("sys_user_role_t")
public class SysUserRole implements Serializable {
    /**
     * 主键ID
     *
     * Table:     sys_user_role
     * Column:    id
     * Nullable:  false
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 用户ID
     *
     * Table:     sys_user_role
     * Column:    user_id
     * Nullable:  true
     */
    private Long userId;

    /**
     * 企业编号
     *
     * Table:     sys_user
     * Column:    comSerial
     * Nullable:  true
     */
    private String comSerial;

    /**
     * 企业id
     *
     * Table:     sys_user
     * Column:    comSerialId
     * Nullable:  true
     */
    private Long comSerialId;
    /**
     * 角色ID
     *
     * Table:     sys_user_role
     * Column:    role_id
     * Nullable:  true
     */
    private Long roleId;

    /**
     * 生效时间
     *
     * Table:     sys_user_role
     * Column:    effect_start_date
     * Nullable:  true
     */
    private Date effectStartDate;

    /**
     * 失效时间
     *
     * Table:     sys_user_role
     * Column:    effect_end_date
     * Nullable:  true
     */
    private Date effectEndDate;

    /**
     * 创建人
     *
     * Table:     sys_user_role
     * Column:    created_by
     * Nullable:  true
     */
    private Long createdBy;

    /**
     * 创建时间
     *
     * Table:     sys_user_role
     * Column:    created_date
     * Nullable:  true
     */
    private Date createdDate;

    /**
     * 修改人
     *
     * Table:     sys_user_role
     * Column:    updated_by
     * Nullable:  true
     */
    private Long updatedBy;

    /**
     * 修改时间
     *
     * Table:     sys_user_role
     * Column:    updated_date
     * Nullable:  true
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_role
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    public SysUserRole(Long id, Long userId, Long roleId, Date effectStartDate, Date effectEndDate, Long createdBy, Date createdDate, Long updatedBy, Date updatedDate,String comSerial,Long comSerialId) {
        this.id = id;
        this.userId = userId;
        this.roleId = roleId;
        this.effectStartDate = effectStartDate;
        this.effectEndDate = effectEndDate;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.updatedBy = updatedBy;
        this.updatedDate = updatedDate;
        this.comSerial = comSerial;
        this.comSerialId = comSerialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    public SysUserRole() {
        super();
    }
}
