package com.struggler.common.model;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.IdType;
import lombok.Data;

import java.util.Date;

/**
 * Table: sys_user_dept
 */
@Data
@TableName("sys_user_dept")
public class SysUserDept extends BaseModel {
    /**
     * 主键ID
     *
     * Table:     sys_user_org
     * Column:    id
     * Nullable:  false
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 用户ID
     *
     * Table:     sys_user_org
     * Column:    user_id
     * Nullable:  true
     */
    private Long userId;

    /**
     * 组织ID
     *
     * Table:     sys_user_org
     * Column:    org_id
     * Nullable:  true
     */
    private Long deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_org
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_org
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    public SysUserDept(Long id, Long userId, Long deptId, Long createdBy, Date createdDate, Long updatedBy, Date updatedDate) {
        this.id = id;
        this.userId = userId;
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_org
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    public SysUserDept() {
        super();
    }
}
