package com.struggler.common.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.annotations.TableName;
import com.baomidou.mybatisplus.enums.IdType;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Date;

/**
 * Table: sys_user
 */
@Data
@TableName("sys_user")
public class SysUser extends BaseModel {
    /**
     * 用户id
     * <p>
     * Table:     sys_user
     * Column:    id
     * Nullable:  false
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 账号
     * <p>
     * Table:     sys_user
     * Column:    account
     * Nullable:  true
     */
    private String account;

    /**
     * 密码
     * <p>
     * Table:     sys_user
     * Column:    password
     * Nullable:  true
     */
    private String password;

    /**
     * 全名
     * <p>
     * Table:     sys_user
     * Column:    user_name
     * Nullable:  true
     */
    private String userName;

    /**
     * 邮箱
     * <p>
     * Table:     sys_user
     * Column:    email
     * Nullable:  true
     */
    private String email;

    /**
     * 员工编号
     * <p>
     * Table:     sys_user
     * Column:    employee_number
     * Nullable:  true
     */
    private String employeeNumber;

    /**
     * 电话
     * <p>
     * Table:     sys_user
     * Column:    phone_number
     * Nullable:  true
     */
    private String phoneNumber;

    /**
     * 状态 01启用 02 锁定  03 禁用
     * <p>
     * Table:     sys_user
     * Column:    status
     * Nullable:  true
     */
    private String del;

    /**
     * Table:     sys_user
     * Column:    given_name
     * Nullable:  true
     */
    private String givenName;

    /**
     * 姓氏
     * <p>
     * Table:     sys_user
     * Column:    surname
     * Nullable:  true
     */
    private String surname;

    /**
     * 别名
     * <p>
     * Table:     sys_user
     * Column:    alias_name
     * Nullable:  true
     */
    private String aliasName;

    /**
     * 银行名称
     * <p>
     * Table:     sys_user
     * Column:    bank_name
     * Nullable:  true
     */
    private String bankName;

    /**
     * 银行账号
     * <p>
     * Table:     sys_user
     * Column:    bank_account_number
     * Nullable:  true
     */
    private String bankAccountNumber;

    /**
     * 用户类型 01普通用户 02管理员
     * <p>
     * Table:     sys_user
     * Column:    user_type
     * Nullable:  true
     */
    private String userType;

    /**
     * 最后登录时间
     * <p>
     * Table:     sys_user
     * Column:    last_login_time
     * Nullable:  true
     */
    @JSONField(format="yyyy-MM-dd HH:mm:ss")
    @JsonFormat
    private Date lastLoginTime;

    /**
     * 是否邮箱提醒  Y 提醒  N 不提醒
     * <p>
     * Table:     sys_user
     * Column:    email_remind
     * Nullable:  false
     */
    private String emailRemind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    public SysUser(Long id, String account, String password, String userName, String email, String employeeNumber, String phoneNumber,  String del, String givenName, String surname, String aliasName, String bankName, String bankAccountNumber, String userType, Date lastLoginTime, String emailRemind) {
        this.id = id;
        this.account = account;
        this.password = password;
        this.userName = userName;
        this.email = email;
        this.employeeNumber = employeeNumber;
        this.phoneNumber = phoneNumber;
        this.del = del;
        this.givenName = givenName;
        this.surname = surname;
        this.aliasName = aliasName;
        this.bankName = bankName;
        this.bankAccountNumber = bankAccountNumber;
        this.userType = userType;
        this.lastLoginTime = lastLoginTime;
        this.emailRemind = emailRemind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Tue Jun 04 14:37:07 CST 2019
     */
    public SysUser() {
        super();
    }
}
